# Generated by Django 5.1.6 on 2025-02-22 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_panorama_remove_scenehotspot_scene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Color o acabado principal', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación del registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad (cm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento (opcional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura (cm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el producto está disponible para la venta'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Material principal (madera, metal, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=django.utils.timezone.now, help_text='Código único de inventario (SKU)', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho (cm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo del mueble', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta', max_digits=10),
        ),
    ]
