# Generated by Django 5.1.6 on 2025-02-20 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Identificador único para Pannellum', unique=True)),
                ('image', models.ImageField(upload_to='panoramas/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='panorama',
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='SceneHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scene', 'Ir a otra escena'), ('product', 'Ver producto')], default='product', max_length=20)),
                ('pitch', models.FloatField(help_text='Ángulo vertical (-90 a 90)')),
                ('yaw', models.FloatField(help_text='Ángulo horizontal (-180 a 180)')),
                ('text', models.CharField(blank=True, help_text='Texto del hotspot', max_length=255)),
                ('product', models.ForeignKey(blank=True, help_text="Producto asociado si es un hotspot de tipo 'product'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='shop.panoramascene')),
                ('target_scene', models.ForeignKey(blank=True, help_text="Escena a la que se navega si es un hotspot de tipo 'scene'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.panoramascene')),
            ],
        ),
        migrations.DeleteModel(
            name='Panorama',
        ),
        migrations.DeleteModel(
            name='Hotspot',
        ),
    ]
