# Generated by Django 5.1.6 on 2025-02-20 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_panoramascene_remove_hotspot_panorama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Identificador único para la escena', unique=True)),
                ('image', models.ImageField(upload_to='panoramas/', verbose_name='Imagen 360 (JPG)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.RemoveField(
            model_name='scenehotspot',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='scenehotspot',
            name='target_scene',
        ),
        migrations.RemoveField(
            model_name='scenehotspot',
            name='product',
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'Producto'), ('scene', 'Escena')], default='product', max_length=20)),
                ('x', models.FloatField(help_text='Valor entre 0 y 100', verbose_name='Coordenada X')),
                ('y', models.FloatField(help_text='Valor entre 0 y 100', verbose_name='Coordenada Y')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción del Hotspot')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('connected_panorama', models.ForeignKey(blank=True, help_text="Panorama al que se navega si el hotspot es de tipo 'scene'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_hotspots', to='shop.panorama')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='shop.panorama')),
            ],
        ),
        migrations.DeleteModel(
            name='PanoramaScene',
        ),
        migrations.DeleteModel(
            name='SceneHotspot',
        ),
    ]
